import { Skeleton, Stack } from "@chakra-ui/react";

export const RepositoriesSkeleton = () => (
  <Stack>
    <Skeleton
      borderRadius={4}
      endColor="gray.800"
      h={100}
      startColor="gray.600"
    />
    <Skeleton
      borderRadius={4}
      endColor="gray.800"
      h={100}
      startColor="gray.600"
    />
    <Skeleton
      borderRadius={4}
      endColor="gray.800"
      h={100}
      startColor="gray.600"
    />
    <Skeleton
      borderRadius={4}
      endColor="gray.800"
      h={100}
      startColor="gray.600"
    />
    <Skeleton
      borderRadius={4}
      endColor="gray.800"
      h={100}
      startColor="gray.600"
    />
    <Skeleton
      borderRadius={4}
      endColor="gray.800"
      h={100}
      startColor="gray.600"
    />
    <Skeleton
      borderRadius={4}
      endColor="gray.800"
      h={100}
      startColor="gray.600"
    />
    <Skeleton
      borderRadius={4}
      endColor="gray.800"
      h={100}
      startColor="gray.600"
    />
    <Skeleton
      borderRadius={4}
      endColor="gray.800"
      h={100}
      startColor="gray.600"
    />
    <Skeleton
      borderRadius={4}
      endColor="gray.800"
      h={100}
      startColor="gray.600"
    />
  </Stack>
);
